examenes/urls.py
from django.conf.urls import url 
from . import views 
from django.urls import path
from .views import *
from django.urls import include
app_name='oppositionexams'

urlpatterns =[
    url(r'^$',views.index,name="index"),
    url(r'^nosotros/$',views.nosotros,name="nosotros"),
    url(r'^lista/$',views.lista_examenes,name="lista"),
    url(r'^lista/(?P<pk>\d+)$',views.examen_view,name="examen"),
    url(r'^lista/(?P<pk>\d+)/data/$',views.ver_datos_view,name="ver-datos"),
    url(r'^lista/(?P<pk>\d+)/save/$',views.guardar_examen_view,name="guardar"),
    url(r'^register/$', views.register, name='register'),
    

    url(r'^policia/$',views.policia,name="policia"),
    url(r'^perfil/$',views.perfil,name="perfil"),
    url(r'^policia/(?P<pk>\d+)$',views.examen_view,name="examen"),
    url(r'^policia/(?P<pk>\d+)/data/$',views.ver_datos_view,name="ver-datos"),
    url(r'^policia/(?P<pk>\d+)/save/$',views.guardar_examen_view,name="guardar"),
]
urlpatterns += [
    url(r'^policia/conocimiento/$',views.policia_conociiento,name="pconocimiento"),
    url(r'^policia/conocimiento/(?P<pk>\d+)$',views.examen_view,name="examen"),
    url(r'^policia/conocimiento/(?P<pk>\d+)/data/$',views.ver_datos_view,name="ver-datos"),
    url(r'^policia/conocimiento/(?P<pk>\d+)/save/$',views.guardar_examen_view,name="guardar"),
]

urlpatterns += [
    url(r'^policia/ortografia/$',views.policia_ortografia,name="portografia"),
    url(r'^policia/ortografia/(?P<pk>\d+)$',views.examen_view,name="examen"),
    url(r'^policia/ortografia/(?P<pk>\d+)/data/$',views.ver_datos_view,name="ver-datos"),
    url(r'^policia/ortografia/(?P<pk>\d+)/save/$',views.guardar_examen_view,name="guardar"),
]
urlpatterns += [
    url(r'^policia/psicotecnico/$',views.policia_psicotecnico,name="psicotecnico"),
    url(r'^policia/psicotecnico/(?P<pk>\d+)$',views.examen_view,name="examen"),
    url(r'^policia/psicotecnico/(?P<pk>\d+)/data/$',views.ver_datos_view,name="ver-datos"),
    url(r'^policia/psicotecnico/(?P<pk>\d+)/save/$',views.guardar_examen_view,name="guardar"),
]
urlpatterns += [
    url(r'^guardia/$',views.guardia,name="guardia"),    
    url(r'^guardia/(?P<pk>\d+)$',views.examen_view,name="examen"),
    url(r'^guardia/(?P<pk>\d+)/data/$',views.ver_datos_view,name="ver-datos"),
    url(r'^guardia/(?P<pk>\d+)/save/$',views.guardar_examen_view,name="guardar"),
]

urlpatterns += [
    url(r'^guardia/conocimiento/$',views.guardia_conocimiento,name="gconocimiento"),
    url(r'^guardia/conocimiento/(?P<pk>\d+)$',views.examen_view,name="examen"),
    url(r'^guardia/conocimiento/(?P<pk>\d+)/data/$',views.ver_datos_view,name="ver-datos"),
    url(r'^guardia/conocimiento/(?P<pk>\d+)/save/$',views.guardar_examen_view,name="guardar"),
]
urlpatterns += [
    url(r'^guardia/ortografia/$',views.guardia_ortografia,name="gortografia"),
    url(r'^guardia/ortografia/(?P<pk>\d+)$',views.examen_view,name="examen"),
    url(r'^guardia/ortografia/(?P<pk>\d+)/data/$',views.ver_datos_view,name="ver-datos"),
    url(r'^guardia/ortografia/(?P<pk>\d+)/save/$',views.guardar_examen_view,name="guardar"),
]

urlpatterns += [
    url(r'^guardia/psicotecnico/$',views.guardia_psicotecnico,name="gpsicotecnico"),
    url(r'^guardia/psicotecnico/(?P<pk>\d+)$',views.examen_view,name="examen"),
    url(r'^guardia/psicotecnico/(?P<pk>\d+)/data/$',views.ver_datos_view,name="ver-datos"),
    url(r'^guardia/psicotecnico/(?P<pk>\d+)/save/$',views.guardar_examen_view,name="guardar"),
]

urlpatterns += [
    url(r'^signup/$', views.signup, name='signup'),
    path('activate/<slug:uidb64>/<slug:token>/',views.activate, name="activate"),
]

oppositionexams/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.auth import views as reset

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oppositionexams/', include('examenes.urls')),
    path('',RedirectView.as_view(url='/oppositionexams/', permanent=True)),
    path('accounts/',include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

examenes/models.py
from django.db import models

# Create your models here.
from django.core.exceptions import ValidationError,ImproperlyConfigured
from django.core.validators import (
    MaxValueValidator, validate_comma_separated_integer_list,
)
from django.utils.translation import ugettext_lazy as _ 
from django.utils.timezone import now 
import random 
from django.contrib.auth.models import User


class CategoriaManager(models.Manager):
    def nueva_categoria(self,categoria):
        nueva_categoria = self.create(categoria=re.sub('\s+','-',categoria))
        nueva_categoria.save()
        return nueva_categoria
class Categoria(models.Model):
    categoria = models.CharField(verbose_name=_("Categoría"),max_length=250,blank=True,unique=True,null=True)
    objects = CategoriaManager()

    class Meta:
        verbose_name=_("Categría")
        verbose_name_plural=_("Categorias")
    def __str__(self):
        return self.categoria

class SubCategoria(models.Model):
    sub_categoria = models.CharField(verbose_name=_("Sub-Categoría"),max_length=250,blank=True, null=True)
    categoria = models.ForeignKey(Categoria, null=True, blank=True, verbose_name=_("Categoría"), on_delete=models.CASCADE)
    objects = CategoriaManager()

    class Meta:
        verbose_name=_("Sub-Categoría")
        verbose_name_plural=_("Sub-Categorias")
    def __str__(self):
        return self.sub_categoria+"("+self.categoria.categoria+")"

class Examen(models.Model):
    nombre = models.CharField(max_length=250)
    categoria = models.ForeignKey(Categoria, null=True, blank=True, verbose_name=_("Categoría"), on_delete= models.CASCADE)
    sub_categoria = models.ForeignKey(SubCategoria, null=True, blank=True, verbose_name=_("Sub-Categoría"), on_delete= models.CASCADE)
    numero_de_preguntas = models.IntegerField()
    tiempo = models.IntegerField(help_text="Duración del examen en minutos")
    puntuacion_para_pasar = models.IntegerField(help_text="Puntuación necesaria para aprobar")

    def __str__(self):
        return self.nombre+"("+self.categoria.categoria+" Tipo: "+self.sub_categoria.sub_categoria+")"
    def get_preguntas(self):
        preguntas = list(self.pregunta_set.all())
        random.shuffle(preguntas)
        return preguntas[:self.numero_de_preguntas]
    class Meta:
        verbose_name_plural=_("Examenes")

examenes/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import Textarea

class CustomerUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields+("email",)


from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class SignupForm(UserCreationForm):   
    class Meta:
        model = User
        fields = ('email', 'first_name','last_name','username')


class ContactForm(forms.Form):
    name = forms.CharField(label='Nombre',)
    subject = forms.CharField(label='Asunto')
    email = forms.EmailField(label='Tú Correo electrónico',)
    message = forms.CharField(label='Mensaje',widget=Textarea,)

examenes/views.py
from django.contrib.auth.backends import UserModel
from django.shortcuts import render
from .models import *

from django.views import generic
import datetime
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from preguntas.models import Pregunta,Respuesta
from resultados.models import Resultado

# Create your views here.

def index(request):
    categoria = Categoria.objects.all()
    context = {'categorias':categoria}
    return render(request,'index.html',context)

def lista_examenes(request):
    examen_policia = Examen.objects.filter(categoria=1)
    examen_guardia = Examen.objects.filter(categoria=2)
    context = {'examen_policia':examen_policia,'examen_guardia':examen_guardia}
    return render(request,'lista.html',context)
def examen_view(request,pk):
    examen = Examen.objects.get(pk=pk)
    return render(request,'examen.html',{'obj':examen})

def ver_datos_view(request,pk):
    examen = Examen.objects.get(pk=pk)
    preguntas = []
    for p in examen.get_preguntas():
        respuestas = []
        for r in p.get_respuestas():
            respuestas.append(r.respuesta)
        preguntas.append({str(p):respuestas})
    return JsonResponse({
        'data':preguntas,
        'time':examen.tiempo,
    })

from datetime import date 
from datetime import datetime

def guardar_examen_view(request,pk):
    if request.is_ajax():
        preguntas = []
        data = request.POST 
        data_ = dict(data.lists())
        data_.pop('csrfmiddlewaretoken')

        for q in data_.keys():
            pregunta = Pregunta.objects.get(texto=q)
            preguntas.append(pregunta)

            
            
        usuario = request.user 
        examen = Examen.objects.get(pk=pk)

        score = 0
        total = 0
        numero_preguntas = examen.numero_de_preguntas
        numero_errores = 0
        numero_aciertos = 0
        pregu = 10/numero_preguntas
        multiplier = 100/examen.numero_de_preguntas
        resultados = []
        respuesta_correcta = None 
        no_sabe=0
        for p in preguntas:
            r_selected = request.POST.get(str(p))
            if r_selected !="":
                respuesta_pregunta = Respuesta.objects.filter(pregunta=p)
                for a in respuesta_pregunta:
                    if r_selected == a.respuesta:
                        if a.correcta:
                            score +=1
                            numero_aciertos +=1
                            respuesta_correcta = a.respuesta
                    elif r_selected =='NS/NC':
                        if a.correcta:
                            no_sabe +=1
                            respuesta_correcta = a.respuesta 
                    else:
                        if a.correcta:
                            numero_errores += 1
                            respuesta_correcta = a.respuesta 
                resultados.append({str(p):{'Respuesta_correcta':respuesta_correcta,'respuesta':r_selected}})
            else:
                resultados.append({str(p):'No respondida'})
        score_=score*multiplier
        mal = float(numero_errores/2)
        total=float((numero_aciertos-mal)*pregu)
        fecha_examen=datetime.now()
        if total<0:
            total=0
        Resultado.objects.create(examen=examen,usuario=usuario,nota=total,fecha=fecha_examen)

        if total>=examen.puntuacion_para_pasar:
            return JsonResponse({'pasar':True,'nota':total,'resultados':resultados})
        else:
            return JsonResponse({'pasar':False,'nota':total,'resultados':resultados})

from django.contrib.auth import login 
from django.shortcuts import redirect, render 
from django.urls import reverse 
from examenes.forms import CustomerUserCreationForm

def register(request):
    if request.method == "GET":
        return render(
            request,"oppositionexams/register.html",
            {"form":CustomerUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomerUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
        return redirect('oppositionexams:index')




def policia(request):
    examen_policia = Examen.objects.filter(categoria=1)
    context = {'examen_policia':examen_policia}
    return render(request,'oppositionexams/policia.html',context)
def guardia(request):
    examen_guardia = Examen.objects.filter(categoria=2)
    context = {'examen_guardia':examen_guardia}
    return render(request,'oppositionexams/guardia.html',context)
def policia_conociiento(request):
    examen = Examen.objects.filter(categoria=1)
    examen_policia=examen.filter(sub_categoria=1)
    context = {'examen_policia':examen_policia}
    return render(request,'oppositionexams/pconocimiento.html',context)
def policia_ortografia(request):
    examen = Examen.objects.filter(categoria=1)
    examen_policia=examen.filter(sub_categoria=2)
    context = {'examen_policia':examen_policia}
    return render(request,'oppositionexams/portografia.html',context)
def policia_psicotecnico(request):
    examen = Examen.objects.filter(categoria=1)
    examen_policia=examen.filter(sub_categoria=5)
    context = {'examen_policia':examen_policia}
    return render(request,'oppositionexams/ppsicotecnico.html',context)
def guardia_conocimiento(request):
    examen = Examen.objects.filter(categoria=2)
    examen_guardia = examen.filter(sub_categoria=3)
    context = {'examen_guardia':examen_guardia}
    return render(request,'oppositionexams/gconocimiento.html',context)
def guardia_ortografia(request):
    examen = Examen.objects.filter(categoria=2)
    examen_guardia = examen.filter(sub_categoria=4)
    context = {'examen_guardia':examen_guardia}
    return render(request,'oppositionexams/gortografia.html',context)
def guardia_psicotecnico(request):
    examen = Examen.objects.filter(categoria=2)
    examen_guardia = examen.filter(sub_categoria=6)
    context = {'examen_guardia':examen_guardia}
    return render(request,'oppositionexams/gpsicotecnico.html',context)


def perfil(request):
    usuario = request.user
    resultados = Resultado.objects.filter(usuario=usuario)
    resultao=resultados.all()
    context = {'usuario':usuario,'resultados':resultao}
    return render(request,'oppositionexams/perfil.html',context)

'''

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignupForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')
'''

from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

UserModel = get_user_model()
from .forms import SignupForm
from .tokens import account_activation_token

from django.core.mail import send_mail
from django.conf import settings

def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html')
    if request.method == 'POST':
        form = SignupForm(request.POST)
        # print(form.errors.as_data())
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            subject = "Confirmación Registro"
            current_site = get_current_site(request)
            mensaje = render_to_string('acc_active_email.html',{
                'user':user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':default_token_generator.make_token(user),
            })

examenes/templates/acc_active_email.html
{% autoescape off %}
Hola {{ user.username }},
Haz click en el enlace que se te proporciona a continuación para completar el registro,http://{{ domain }}{% url 'oppositionexams:activate' uidb64=uid token=token %}
{% endautoescape %}

examenes/templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% block scripts %} 
{% endblock scripts %}
    <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title>Opposition Exams</title>
  <meta name="description" content="Free Responsive Html5 Css3 Templates | Zerotheme.com">
  <meta name="author" content="https://www.zerotheme.com">
  
  <!-- Mobile Specific Metas
  ================================================== -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  
  <!-- CSS
  ================================================== -->

    <link rel="stylesheet" href="{% static 'css/zerogrid.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
  <!-- Custom Fonts -->
  <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  
  
  <link rel="stylesheet" href="{% static 'css/menu.css' %}">
  <script src="{% static 'js/jquery1111.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/script.js' %}"></script>
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <!-- Owl Carousel Assets -->
  <link href="{% static 'owl-carousel/owl.carousel.css' %}" rel="stylesheet">
  
  <!--[if lt IE 8]>
     <div style=' clear: both; text-align:center; position: relative;'>
       <a href="http://windows.microsoft.com/en-US/internet-explorer/Items/ie/home?ocid=ie6_countdown_bannercode">
         <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
      </a>
    </div>
  <![endif]-->
  <!--[if lt IE 9]>
      <script src="js/html5.js"></script>
      <script src="js/css3-mediaqueries.js"></script>
  <![endif]-->
  
</head>

<body class="home-page">
  <div class="wrap-body">
      <header>

          <div class="logo">
              <a href="{% url 'oppositionexams:index' %}">Opposition Exams</a>
              <span>Plataforma para hacer examenes tipo test</span>
          </div>
          <div id="cssmenu" class="t-left prueba">
              <ul>
                 <li class="active"><a href="{% url 'oppositionexams:index' %}"><span>Inicio</span></a></li>
                 <li class="has-sub"><a href="{% url 'oppositionexams:policia' %}"><span>Policia Nacional</span></a>
                    <ul>
                       <li class="has-sub"><a href="{% url 'oppositionexams:pconocimiento' %}"><span>Conocimiento</span></a></li>
                       <li class="has-sub"><a href="{% url 'oppositionexams:portografia' %}"><span>Ortografia</span></a></li>
                       <li class="has-sub"><a href="{% url 'oppositionexams:psicotecnico' %}"><span>Psicotécnicos</span></a></li>
                    </ul>
                 </li>
                 <li class="has-sub"><a href="{% url 'oppositionexams:guardia' %}"><span>Guardia Civil</span></a>
                    <ul>
                       <li class="has-sub"><a href="{% url 'oppositionexams:gconocimiento' %}"><span>Conocimiento</span></a></li>
                       <li class="has-sub"><a href="{% url 'oppositionexams:gortografia' %}"><span>Ortografia</span></a></li>
                       <li class="has-sub"><a href="{% url 'oppositionexams:gpsicotecnico' %}"><span>Psicotécnicos</span></a></li>
                    </ul>
                 </li>
                 <li><a href="{% url 'oppositionexams:lista' %}"><span>Todos los examenes</span></a></li>

                 {% if user.is_authenticated %}
                                <li><a href="{% url 'oppositionexams:perfil' %}">Mi Perfil</a></li>
                                <li><a href="{% url 'logout' %}">Cerrar Sesión</a></li>
                {% else %}
                                <li><a href="{% url 'login' %}">Iniciar Sesión</a></li>
                                <li><a href="{% url 'oppositionexams:signup' %}">Registrarse</a></li>
                {% endif %}

                 <li><a href="{% url 'oppositionexams:nosotros' %}"><span>Nosotros</span></a></li>

              </ul>
          </div>

          
      {% block content %}

      {% endblock %}
      <!--////////////////////////////////////Footer-->
      <footer>
          <div class="zerogrid wrap-footer">
              <div class="row justify-content-around">
                  <div class="col-1-4 col-footer-1">
                      <div class="wrap-col">
                          <h3 class="widget-title">Sobre Nosotros</h3>
                          <p>Opposition Exams es el proyecto final de una alumna del grado superior de Desarrollo de Aplicaciones Web</p>
                          <p>El objetivo principal de esta plataforma, es que los usuario puedan hacer examenes de distintas oposiciones de forma gratuita, solo tienen que
                              registrarse en la aplicación
                          </p>
                      </div>
                  </div>

                  <div class="col-1-4 col-footer-3">
                      <div class="wrap-col">
                          <h3 class="widget-title">Información Adicional</h3>
                          <p>Los examenes de esta plataforma solo lo podrán hacer aquellas personas que se hallan registrado previamente</p>
                          <p>Las preguntas que aparezcan serán las que han aparecido en años anteriores </p>
                      </div>
                  </div>

              </div>
          </div>

      </footer>
      
      <!-- carousel -->
      <script src="{% static 'owl-carousel/owl.carousel.js' %}"></script>
      <script>
      $(document).ready(function() {
        $("#owl-slide").owlCarousel({
          autoPlay: 3000,
          items : 1,
          itemsDesktop : [1199,1],
          itemsDesktopSmall : [979,1],
          itemsTablet : [768, 1],
          itemsMobile : [479, 1],
          navigation: true,
          navigationText: ['<i class="fa fa-chevron-left fa-5x"></i>', '<i class="fa fa-chevron-right fa-5x"></i>'],
          pagination: false
        });
      });
      </script>
      <style>
          .alinear{
              text-align:justify;
              margin: 0.5vw;
          }
          .bloque{
              margin: 0.5vw;
          }
          .usuarios{
              width: 25vw;
              text-align:justify;
              margin-left: 38%;
          }
          table{
              border-collapse: collapse;
              width: 50%;
              margin-left: 25%;
              margin-top: 0.5vw;
              margin-bottom: 0.5vw;
          }
          th,td{
              text-align: left;
              padding: 1vw; 
          }
          tr:nth-child(even){
              background-color: grey;
          }
          th{
              background-color: black;
              color:white
          }
          .tabla {
              font-size: 2vw;
              font-style: oblique;
              font-weight: bold;
              font-family: 'Times New Roman', Times, serif;
          }
      </style>
  </div>
</body>
</html>
    

examenes/templates/confirm_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmation</title>
</head>
<body>
{% if success %}
{{ user.username }}, your account is confirmed!
{% else %}
Error, invalid token!
{% endif %}
</body>
</html>

examenes/templates/email_content.html
<p>Usted ha recibido un nuevo mensaje de un usuario:</p>
<dl>
    <dt>Nombre:</dt>
    <dd>{{ name }}</dd>

    <dt>Correo electrónico:</dt>
    <dd>{{ email }}</dd>

    <dt>Mensaje:</dt>
    <dd>{{ message }}</dd>
</dl>

examenes/templates/examen.html
{% extends "base_generic.html" %}
{% load static %}


{% block scripts %} 
<script src="{% static 'js/quiz.js' %}" defer></script>
<link rel="stylesheet" href="{% static 'css/prueba.css' %}">
{% endblock scripts %}

{% block content %} 
<b>{{obj.nombre}}</b>
<p>Puntuación para pasar: {{obj.puntuacion_para_pasar}}</p>
<div class="bloque"><p>Tiempo del examen (minutos): </p><strong><p id="restante">{{obj.tiempo}}</p></strong><p></p></div>
<div id="scorebox" class="score-box"></div>
<div id="resultbox" class="result-box"></div>
<form id="quiz-form" class="mt-3 mb-3 prueba1">
    {% csrf_token %} 
    <div id="quiz-box" class="izquierda"></div>
    <button type="submit" class="btn btn-primary mt-3" onclick="detenerContador()">Terminar</button>
</form>
<form id="finalizar">
    <a href="{% url 'oppositionexams:index' %}"class="not-visible visible" id="boton">Finalizar Revision</a>
    <p></p>
</form>
{% endblock content %}

examenes/templates/nosotros.html
{% extends "base_generic.html" %}
{% load static %}



{% block scripts %} 
<link rel="stylesheet" href="{% static 'css/prueba.css' %}">
{% endblock scripts %}


{% block content %} 
<!-- Button trigger modal -->
<h3>Sobre Nosotros</h3>
<div class="alinear">
<p>Opposition Exams es el proyecto final de una alumna del grado superior de Desarrollo de Aplicaciones Web.El objetivo principal de esta plataforma, es que los usuario puedan hacer examenes de distintas oposiciones de forma gratuita, solo tienen que
    registrarse en la aplicación.Las pruebas que se realizan en esta aplicación estan basadas en las de las distintas oposiciones, pero los métodos de corrección de dichas pruebas 
    son diferentes.
</p>
<p>En esta aplicación cada dos fallos en un examen, da como resultado que una de las preguntas que has acertado no se tiene en cuenta(cada dos mal se quita una bien).</p>
<p>De momento en la aplicación solo disponemos de examenes de dos tipos de oposiciones, pero según la recepción de la aplicación y si los usuarios lo piden se pueden añadir
    examenes de otras oposiciones. Si quieres ponerte en contacto con nosotros para realizarnos alguna queja o sugerencia, lo puedes
    hacer a la siguiente dirección de correo electrónico <strong>oppositionexams@gmail.com</strong>
</p>


<div class="container" style="margin-top: 50px;">
    <div class="row justify-content-center">
      <div class="col-md-5 shadow-sm p-3 mb-5 bg-white rounded" >
        <h2>Formulario Contacto</h2>
        <form method="POST">
          {% csrf_token %} 
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Enviar Correo</button>
        </form>
  
      </div>
  
    </div>
  </div>
{% endblock content %}